name: Docker Image CI
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      rclone_version:
        description: 'A version of rclone image you want to build.'
        default: 'v1.57.0'
        required: true
        type: string
  
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --no-cache --build-arg RCLONE_VERSION=${{ inputs.rclone_version }} -t rclonecron:${{ inputs.rclone_version }} -t rclonecron:latest  .
